USE habits;

CREATE TABLE habits.DayRecord (
  id INT NOT NULL AUTO_INCREMENT,
  habit VARCHAR(255) NOT NULL DEFAULT '',
  date DATETIME NOT NULL,
  dayOfWeek VARCHAR(255) NOT NULL DEFAULT '',
  isDone TINYINT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

CREATE TABLE habits.WeekRecord (
  id INT NOT NULL AUTO_INCREMENT,
  `range` VARCHAR(255) NOT NULL DEFAULT '',
  `from` DATETIME NOT NULL,
  `to` DATETIME NOT NULL,
  habit VARCHAR(255) NOT NULL DEFAULT '',
  desired INT NOT NULL,
  actual INT NOT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB;